language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.4.0
  - 2.3.1
  - 2.2.5
  - 2.1.9
  - 2.0.0
  - 1.9.3
  - jruby-9.1.2.0
  - jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
